---
title: 201121_TIL_Dacon
categories: TIL dacon
tags: dacon NLP
last_modified_at: 2020-11-21 16:28:00 -0500
---

## Dacon Author Classfication 2일차

* 모델을 다시 만들어보는 날

* 어제 보고 실패했던 [Kaggle Notebook](https://www.kaggle.com/rajmehra03/a-complete-text-classfication-guide-word2vec-lstm)을 참고해보자.

## 전처리

* 전처리 과정 코드를 다시 수정했다. 아래와 같음.

```python
X_train = []
for sentence in train_data['text']:
    temp_X = []
    temp_X = sentence.lower().split()
    remove_stopwords(temp_X)
    temp_X = [lemmatizer.lemmatize(word) for word in temp_X]
    temp_X = [lemmatizer.lemmatize(word, "v") for word in temp_X]
    X_train.append(temp_X)
```

* 이유는 모르겠는데, 이렇게 하니까 정규화가 제대로 안 되었다!!! 과거형 그대로 남아 있다.

* 왜 정규화가 제대로 안 된 것 같지? 했었는데 이 코드를 추가했어야 했다.([참고 자료](https://wikidocs.net/21707))

```python
temp_X = [lemmatizer.lemmatize(word, "v") for word in temp_X]
```

## 정수 인코딩 및 패딩

* 정수 인코딩에서 단어는 버리지 않고 모두 사용하기로 하였다. (빈도수가 낮더라도)

* 분명 온점과 반점을 살렸던 것 같은데 중간 과정에서 사라져버렸다 ㅜㅜ

```python
tokenizer = Tokenizer()
tokenizer.fit_on_texts(X_train)
vocab_size = 57718
max_len = 480
below_threshold_len(max_len, X_train)
train_sequences = tokenizer.texts_to_sequences(X_train)
train_padded = pad_sequences(train_sequences, padding=padding_type, maxlen=max_len)
test_sequences = tokenizer.texts_to_sequences(X_test)
test_padded = pad_sequences(test_sequences, padding=padding_type, maxlen=max_len)
```



## 모델 학습

*  [text Classfication Kaggle Notebook](https://www.kaggle.com/rajmehra03/a-complete-text-classfication-guide-word2vec-lstm), [IMDB Notebook](https://www.kaggle.com/nilanml/imdb-review-deep-model-94-89-accuracy)과 [네이버 영화 리뷰 분류](https://wikidocs.net/44249) 참고하였음.

```python
model = Sequential()
model.add(Embedding(vocab_size, 256))
model.add(LSTM(128))
model.add(Dense(16, activation = 'relu'))
model.add(Dropout(0.20))
model.add(Dense(5, activation="softmax"))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
history = model.fit(train_padded, y_train, epochs=10, batch_size=60, validation_split=0.2)
```

## 에러 발생

* `ValueError: Shapes (None, 1) and (None, 5) are incompatible` 이런 내용의 에러가 발생했다.

* 계속 모델 학습을 수정해도 반복... ㅜㅜ

* 내일 스터디원분께 한번 피드백 받아보고 수정하고, 다시 학습해야겠다.
